name: "Logi Host Switch"
description: "Switch Logitech mouse host via Home Assistant using a Unifying/Bolt USB receiver"
version: "0.1.9"
slug: "ha_logi_host"
url: "https://github.com/dani-rodr/ha-logi-host"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: system
boot: auto
full_access: true
privileged:
  - SYS_RAWIO
apparmor: false
udev: true
services:
  - "mqtt:need"
options:
  receiver_type: "unifying"
  log_level: "info"
schema:
  receiver_type: "list(unifying|bolt)"
  device_path: "str?"
  log_level: "list(debug|info|warning|error)"
